# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56b5c977ff127ac75609743cc495e04a2359de22cfa26d8e7e01951b0c18d794dc1b65f5f563c22626deeafb86e12f67857d4b941ed96c98a769c84bc0440d3c

test:
  secret_key_base: e3ccb86202796a203b0adb5e38842c82468e9aba028f05dbb8136a4a0fd51020073d1f3dcf5e81030db2f3c8aeeabdc74b321bf3386473ef09ee7bfa756a5f7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
